#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Katas\GameOfLifeCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GameOfLifeCommand());

$application->run();
